<?php

/**
* Implementation of hook_menu().
*/
function pets_cats_menu() {
  return array(
    'cats' => array(
      'title' => 'Cats',
      'page callback' => 'pets_cats_select',
      'access callback' => TRUE, // Just let anyone see it.
      'type' => MENU_NORMAL_ITEM, // Menu entry with a navigation entry.
    ),
    'cats/add' => array(
      'title' => 'Add',
      'page callback' => 'pets_cats_add',
      'page arguments' => array(1),
      'access callback' => 'user_access',
      'type' => MENU_CALLBACK, // No navigation entry, just handle the request.
      'access arguments' => array('administer access control'),
    ),   
    'cats/%' => array(
      'title' => 'Cats',
      'page callback' => 'pets_cats_about',
      'page arguments' => array(1),
      'access callback' => TRUE, // Just let anyone see it.
      'type' => MENU_CALLBACK, // No navigation entry, just handle the request.
    ),
    'cats/%/description' => array(
      'title' => 'About',
      'page callback' => 'pets_cats_about',
      'page arguments' => array(1),
      'access callback' => TRUE, // Just let anyone see it.
      'type' => MENU_DEFAULT_LOCAL_TASK, // Default tab entry. This will show up when you visit the parent cats.
    ),
    'cats/%/maintnence' => array(
      'title' => 'Maintnence',
      'page callback' => 'pets_cats_maint',
      'page arguments' => array(1),
      'access callback' => TRUE, // Just let anyone see it.
      'type' => MENU_LOCAL_TASK, // Tab entry
    ),
    'cats/%/pics' => array(
      'title' => 'Pictures',
      'page callback' => 'pets_cats_pics',
      'page arguments' => array(1),
      'access callback' => TRUE, // Just let anyone see it.
      'type' => MENU_LOCAL_TASK, // Tab entry
    ),
    'cats/%/costs' => array(
      'title' => 'Costs',
      'page callback' => 'pets_cats_costs',
      'page arguments' => array(1),
      'access callback' => TRUE, // Just let anyone see it.
      'type' => MENU_LOCAL_TASK, // Tab entry
    ), 
  );
}

/**
* Valid permissions for this module
* @return array An array of valid permissions for the onthisdate module
*/
function pets_cats_perm() {
  return array('access pets_cats content', 'administer pets_cats content');
}

function pets_cats_select() {
	$returnValue = "Please select a cat.<br />";
	
	$result = db_query_range('SELECT * FROM {pets_cats_cats}', 0, 10);
	while ($node = db_fetch_object($result)) {
		$returnValue .= l($node->name, 'cats/' . $node->name) . "<br />";
	}

	return $returnValue;
}

/**
* Menu callback for cats/%/about
*/
function pets_cats_about($cat_id) {
	$output = '';


	
	$result = db_query_range("SELECT * FROM {pets_cats_cats} c WHERE c.name = '$cat_id'", 0, 10);

	if ($node = db_fetch_object($result)) {
		$output .= "This is about Cat " . $node->name . ".<br />";

	
		//$returnValue .= l($node->name, 'cats/' . $node->name) . "<br />";
	}
	else {
		drupal_set_message(t('That cat doesn\'t exist.'));
	}
	
	


  return $output;
}

function pets_cats_maint($cat_id) {
  return "These are the maintnence items for $cat_id";

}

function pets_cats_pics($cat_id) {
  return "Here are some pictures of $cat_id";
}

function pets_cats_costs($cat_id) {
  return "These have been the costs associated with $cat_id";
}

function pets_cats_add($cat_id) {
    $page_content = '';
   
    $page_content .= drupal_get_form('pets_cats_add_form');
	
	return $page_content;
}

function pets_cats_add_form_submit($form, &$form_state) {
	db_query("INSERT INTO {pets_cats_cats} (name, breed, born, recieved, description, cost) VALUES ('%s', '%s', %d, %d, '%s', %f)", 
				$form_state['values']['name'],
				$form_state['values']['breed'],
				mktime(0, 0, 0, $form_state['values']['born']['month'], $form_state['values']['born']['day'], $form_state['values']['born']['year']),
				mktime(0, 0, 0, $form_state['values']['aquired']['month'], $form_state['values']['aquired']['day'], $form_state['values']['aquired']['year']),
				$form_state['values']['description'],
				$form_state['values']['cost']
				);
				
	drupal_set_message(t('Your cat has been saved.'));
}

function pets_cats_add_form($form_state) {
    $form['name'] = array(
        '#type' => 'textfield',
        '#title' => t('Name'),
        '#description' => t("The cat's Name."),
        '#required' => TRUE,
    );
    $form['breed'] = array(
        '#type' => 'textfield',
        '#title' => t('Breed'),
        '#description' => t("The cat's breed."),
    );
	$form['born'] = array(
        '#type' => 'date',
        '#title' => t('Birthdate'),
        '#description' => t("The cat's Birthdate."),
    );
    $form['aquired'] = array(
        '#type' => 'date',
        '#title' => t('Aquired'),
        '#description' => t("The date the cat was aquired."),
    );
    $form['cost'] = array(
        '#type' => 'textfield',
        '#title' => t('Cost'),
        '#description' => t("What the cost was to purchase or adopt."),
    );
	$form['description'] = array(
        '#type' => 'textarea',
        '#title' => t('Description'),
        '#cols' => 50,
        '#rows' => 5,
        '#description' => t("Description of the cat."),
    );
    //Submit button:
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => t('New Cat'),
    );
   
    return $form;
}